<table align="center" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> Inclass-Lab  <br>(Session 3 & 4)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**
6. **[Data Structures with Examples](#Data_Structures)**
7. **[Create and Manipulate the DataFrames](#create_manipulate)**
8. **[Sort](#sorting)**
9. **[Rank](#ranking)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [7]:
import numpy as np
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

arr = np.array([  int(val)   for val in weights  if val > 68  ])
print(type(arr), arr)

<class 'numpy.ndarray'> [74 85 74 70 86 82]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [22]:
import numpy as np
x = np.random.randint(low=10, high=30, size=10)
print(x)

[27 29 28 15 12 25 11 21 13 20]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [34]:
# 3x3 Array
import numpy as np

A = [[1, 4, 8],
     [5, 7, 3],
     [9, 14, 2]]

for i in range(0,3):
    tmp = 0
    for j in range(0, 3):
#        print(i, j, A[j][i])
        tmp = A[j][i] + tmp
    print('Sum of Column[', i, ']: ', tmp)

print(np.sum(A, axis = 0)) # axis = 0: Add columnwise axis = 1: Add row wise...
np.sum(A, axis=0)

Sum of Column[ 0 ]:  15
Sum of Column[ 1 ]:  25
Sum of Column[ 2 ]:  13
[15 25 13]


array([15, 25, 13])

<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [40]:
nparr = np.array(range(0, 20)).reshape(4, 5)
nparr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [59]:
import numpy as np
weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]
we = np.array(weights)
he = np.array(heights)
demo = np.multiply(he, he)
bmi = np.divide(we, demo)
print(bmi)


[22.54657648 22.53061224 19.59645812 21.46915048 26.39797739 20.9572742
 23.922423  ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [76]:
import numpy as np
array1 = [[[3, 4], 
           [8, 2],
           [5, 9]]]
data = [5, 7]
arr = np.array(array1).reshape(3,2)

print(arr)
test = np.append(array1, data)
test.ndim


[[3 4]
 [8 2]
 [5 9]]


1

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [80]:
import numpy as np

M = [[15, 17, 45, 56],
     [7, 42, 15, 63], 
     [54, 3, 61, 41], 
     [0, 87, 16, 20]]


test = np.array(M)
transposed_array = test.T
print('Transposed Array: \n', transposed_array)

Transposed Array: 
 [[15  7 54  0]
 [17 42  3 87]
 [45 15 61 16]
 [56 63 41 20]]


<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [87]:
A1 = [[5, 9],
      [7, 6]]

A2 = [[8,-7],
      [0,4]]

import numpy as np
one = np.stack((A1,A2)) 
one

array([[[ 5,  9],
        [ 7,  6]],

       [[ 8, -7],
        [ 0,  4]]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [92]:
import numpy as np
A1 = [[-81, 75, 40],
      [27, 67, 52]]

A2 = [[15, 54],
      [39, 56]]

one = np.hstack((A1,A2)) 
# Stack arrays in sequence horizontally (column wise).
# This is equivalent to concatenation along the second axis, except for 1-D
# arrays where it concatenates along the first axis. Rebuilds arrays divided
# by `hsplit`.

one

array([[-81,  75,  40,  15,  54],
       [ 27,  67,  52,  39,  56]])

<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [94]:
B = [[8, 7, 0, 9],
     [2, -3, 5, 10],
     [8, 5, -1,3]]

import numpy as np
arr = np.array(B)
np.split(arr, 3)

[array([[8, 7, 0, 9]]), array([[ 2, -3,  5, 10]]), array([[ 8,  5, -1,  3]])]

<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56] L2 = [21, 52, 64, 10, 49, 74, 26] 


In [3]:
import numpy as np 
L1 = [45, 67, 56, 71, 54, 62, 56] 
L2 = [21, 52, 64, 10, 49, 74, 26] 

nparr1 = np.array(L1)
list(zip(L1, L2)) # A zip object yielding tuples until an input is exhausted

[(45, 21), (67, 52), (56, 64), (71, 10), (54, 49), (62, 74), (56, 26)]

<a id='Data_Structures'></a>
## 6. Data Structures with Examples:

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a program to create a dataframe from list of lists
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the below nested list:**<br>

        data = [['Joy', 21], ['Mia', 15], ['Sam', 14]]

In [8]:
import numpy as np
import pandas as pd

data = [['Joy', 21], ['Mia', 15], ['Sam', 14]]

df = pd.DataFrame(data, columns=['Name', 'Age']) 
print(df)

  Name  Age
0  Joy   21
1  Mia   15
2  Sam   14


<a id='create_manipulate'></a>
## 7. Create and Manipulate the DataFrames:

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Split the 'Name' column into two separate columns as First_Name and Last_Name </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Salary</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>3200</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>4500</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>3600</td>
</tr>
<tr>
<td>James Smith</td>
<td>5596</td>
</tr>
   
</table>

In [30]:
dict = {'Name' : ['Emma Larter', 'Mia Junior', 'Sophia Depp', 'James Smith'], 'Salary' : [3200, 4500, 3600, 5596]}
df = pd.DataFrame(dict)
print(df)
test = df.Name.str.split(expand=True)



          Name  Salary
0  Emma Larter    3200
1   Mia Junior    4500
2  Sophia Depp    3600
3  James Smith    5596


0       1
0    Emma  Larter
1     Mia  Junior
2  Sophia    Depp
3   James   Smith

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to select the rows where the sales are higher than 60000 for Mumbai </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [106]:
import pandas as pd
dic = {'Store' : ['A', 'B', 'A', 'C', 'D', 'A', 'D', 'A', 'C', 'B'],
       'Location' : ['Mumbai', 'Pune', 'Hydrabad', 'Mumbai', 'Pune', 'Delhi', 'Hydrabad', 'Pune', 'Mumbai', 'Pune'],
       'Sales' : [40000, 45000, 50000, 90000, 89000, 87000, 85000, 78000, 89000, 70000]}
#print(df[df['Sales'] > 60000])
df.loc[df['Sales'] > 60000]

Store  Location  Sales
3     C    Mumbai  90000
4     D      Pune  89000
5     A     Delhi  87000
6     D  Hydrabad  85000
7     A      Pune  78000
8     C    Mumbai  89000
9     B      Pune  70000

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a program to replace the 'Store' column with the values A, B, C, and D with Store_A,  Store_B, Store_C and Store_D respectively </b>  
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [107]:
df.Store.replace('A', 'Store_A', inplace=True)
df.Store.replace('B', 'Store_B', inplace=True)
df.Store.replace('C', 'Store_C', inplace=True)
df.Store.replace('D', 'Store_D', inplace=True)
df

Store  Location  Sales
0  Store_A    Mumbai  40000
1  Store_B      Pune  45000
2  Store_A  Hydrabad  50000
3  Store_C    Mumbai  90000
4  Store_D      Pune  89000
5  Store_A     Delhi  87000
6  Store_D  Hydrabad  85000
7  Store_A      Pune  78000
8  Store_C    Mumbai  89000
9  Store_B      Pune  70000

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a program to insert a given column at the second position in a dataframe
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Age</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>34</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>59</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>32</td>
</tr>
<tr>
<td>James Smith</td>
<td>40</td>
</tr>
   
</table>

**Add the variable 'Salary' as second column**<br>
            
            Salary = [35000, 24000, 55000, 40000]

In [57]:
import pandas as pd
dict = {"Name" : ['Emma Larter', 'Mia Junior', 'Sophia Depp', 'James Smith'], 
        "Age" : [34, 59, 32, 40]}
Salary = [35000, 24000, 55000, 40000]

df = pd.DataFrame(dict)
df.insert(2, "Salary", Salary)
#0, "col0", pd.Series([5, 6], index=[1, 2])
df

Name  Age  Salary
0  Emma Larter   34   35000
1   Mia Junior   59   24000
2  Sophia Depp   32   55000
3  James Smith   40   40000

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to get the third observation of the given dataframe
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**

<table>
<tr>
<th>Name</th>
<th>Age</th>
</tr>
<tr>
<td>Emma Larter</td>
<td>34</td>
</tr>
<tr>
<td>Mia Junior</td>
<td>59</td>
</tr>
<tr>
<td>Sophia Depp</td>
<td>32</td>
</tr>
<tr>
<td>James Smith</td>
<td>40</td>
</tr>
</table>    

In [80]:
import pandas as pd
data = {"Name" : ['Emma Larter', 'Mia Junior', 'Sophia Depp', 'James Smith'],
        "Age" : [34, 59, 32, 40]}

df = pd.DataFrame(data)
print(df.iloc[2]) # Purely integer-location based indexing for selection by position.

Name    Sophia Depp
Age              32
Name: 2, dtype: object


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to count total sales per store </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [99]:
import pandas as pd
dic = {'Store' : ['A', 'B', 'A', 'C', 'D', 'A', 'D', 'A', 'C', 'B'],
       'Location' : ['Mumbai', 'Pune', 'Hydrabad', 'Mumbai', 'Pune', 'Delhi', 'Hydrabad', 'Pune', 'Mumbai', 'Pune'],
       'Sales' : [40000, 45000, 50000, 90000, 89000, 87000, 85000, 78000, 89000, 70000]}

df = pd.DataFrame(dic)
df.groupby('Store')['Sales'].sum()

Store
A    255000
B    115000
C    179000
D    174000
Name: Sales, dtype: int64

<a id='sorting'></a>
## 8. Sort

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Write a program to sort the dataframe by 'Store' in ascending order and by 'Sales' in descending order simultaneously
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [104]:
df.sort_values(by=['Store', 'Sales'], ascending=[True, False])


Store  Location  Sales
5     A     Delhi  87000
7     A      Pune  78000
2     A  Hydrabad  50000
0     A    Mumbai  40000
9     B      Pune  70000
1     B      Pune  45000
3     C    Mumbai  90000
8     C    Mumbai  89000
4     D      Pune  89000
6     D  Hydrabad  85000

<a id='ranking'></a>
## 9. Rank

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Rank the dataframe in descending order of sales by each store
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the dataframe given below:**
   
<table>
<tr>
<th>Store</th>
<th>Location</th>
<th>Sales</th>
</tr>
<tr>
<td>A</td>
<td>Mumbai</td>
<td>40000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>45000</td>
</tr>
<tr>
<td>A</td>
<td>Hyderabad</td>
<td>50000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>90000</td>
</tr>
<tr>
<td>D</td>
<td>Pune</td>
<td>89000</td>
</tr>
<tr>
<td>A</td>
<td>Delhi</td>
<td>87000</td>
</tr>
<tr>
<td>D</td>
<td>Hyderabad</td>
<td>85000</td>
</tr>
<tr>
<td>A</td>
<td>Pune</td>
<td>78000</td>
</tr>
<tr>
<td>C</td>
<td>Mumbai</td>
<td>89000</td>
</tr>
<tr>
<td>B</td>
<td>Pune</td>
<td>70000</td>
</tr>
   
</table>

In [105]:
df.sort_values(by='Sales',ascending=False)

Store  Location  Sales
3     C    Mumbai  90000
4     D      Pune  89000
8     C    Mumbai  89000
5     A     Delhi  87000
6     D  Hydrabad  85000
7     A      Pune  78000
9     B      Pune  70000
2     A  Hydrabad  50000
1     B      Pune  45000
0     A    Mumbai  40000