## NUMPY

##### NumPy is a Python library used for working with arrays.

##### It also has functions for working in domain of linear algebra, fourier transform, and matrices.

##### NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

##### NumPy stands for Numerical Python.

##### In Python we have lists that serve the purpose of arrays, but they are slow to process.

##### NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

##### The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

##### Arrays are very frequently used in data science, where speed and resources are very important.

##### NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

##### This behavior is called locality of reference in computer science.

##### This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr)) # type is numpy.ndarray

In [ ]:
# 0D Array
import numpy as np
arr = np.array(42)
print(arr)
print(arr.size) # Print the size of the array!!!
print(arr.shape)

In [ ]:
# 1D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.shape)

In [ ]:
# 2D array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.size)
print(arr.shape)
print('ndim: ', arr.ndim)

In [ ]:
# 3D Array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])

print('arr: ', arr)
print('shape: ', arr.shape)
print('size: ', arr.size)
print(arr[0])
print('1, 0 :', arr[1][0])
print('ndim: ', arr.ndim)

arr.ndim

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

In [448]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr.shape)
print('Last element from 2nd dim: ', arr[1, -1])

(2, 5)
Last element from 2nd dim:  10


## SLICING

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])

## Negative Slicing

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3 : -1])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 4])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

In [ ]:
import numpy as np

arr = np.array(['5', '2', '3'], dtype='i')
arr

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

In [ ]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()    # Copy will copy the data.

arr[0] = 42

print(arr)
print(x)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view() # View will create a referece to array.
x[0] = 42

print(arr)
print(x)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 4)

print(newarr)

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1) # this will convert it to single dimension array

print(newarr)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
for x in arr:
  print(x)

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    print('\n')
    for z in y:
      print(z)

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    print('\n')
    for z in y:
      print(z)

In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
help(np.nditer)
for x in np.nditer(arr[:, ::3]):
  print(x)

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

help(np.ndenumerate)

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5])

arr = np.concatenate((arr1, arr2), axis=2)

print(arr)


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=None)


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))

print(arr)

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

In [ ]:
print(dir(np))

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

In [ ]:
x = np.arange(1, 29, step=2)
newarr = np.array_split(x, 3)
print('newarr: ', newarr)
one = np.array_split(newarr[0], 2)
print('one: ', one)

In [ ]:
x = np.arange(1, 17)
newSplit = np.split(x, 4, axis=0)
print('simple split: ', newSplit)

In [ ]:
x = np.arange(16).reshape(4, 4)
print('x : ', x, x.ndim, type(x))

newSplit = np.vsplit(x, 4)
print('simple split: ', newSplit)
print(type(newSplit))


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr % 2 == 0)

print(x)

In [ ]:
x = np.array([1, 2, 4, 5, 7, 9, 12])
print(x)
ind = x.searchsorted(3,side='right')
ind

In [ ]:

x = np.array([1, 2, 4, 5, 7, 9, 12])
print(x)
ind = x.searchsorted(3,side='left')
ind


In [ ]:
x = np.array([1, 2, 4, 5, 7, 9, 12])
print(x)
ind = x.searchsorted(6)
ind

In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

In [ ]:
import numpy as np
a = np.arange(11)
print(a)
#x = np.where(a < 5, a, 10*a)
x = np.where(a < 5, a, 5*a)
print(x)

In [ ]:
import numpy as np
arr = np.array([3, 5, 2, 0, 1, 7, 4, 9, 6, 8])
print(np.sort(arr))

In [ ]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

In [ ]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

In [ ]:
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

In [ ]:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, True]
newarr = arr[x]
print(newarr)

### Filtering 

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
np.cumsum
filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

## Random Number Generation

In [450]:
from numpy import random

x = random.randint(10) # Generate random integer value.
y = random.rand(10)
print(y)
print(x)

[0.81684806 0.7112898  0.41929911 0.22489977 0.49818452 0.31017813
 0.59471792 0.96800518 0.66150243 0.978143  ]
0


In [ ]:
from numpy import random
#x=random.randint(10, 20, size=(10), dtype=int)
x=random.randint(10, 20)
print(type(x))
print(x)



In [ ]:
floatNum = random.rand(3) # Generate 10 float values based on given input. Here 10 float values are created.
floatNum
print(type(floatNum[0]))

### Generate 2D array with Random numbers

In [ ]:
from numpy import random
x = random.randint(100, size=(3, 5))
print(x)

In [ ]:
from numpy import random

x = random.rand(5)

print(x)

In [ ]:
# Generates 2D array of Matrics 3x4
from numpy import random
x = random.rand(3,4)
print(x)

#### choice select the random number from the given array.

In [ ]:
from numpy import random
x = random.choice([3, 5, 7, 9, 10, 12, 15], size=(3,3), replace=False) # choice select the random number from the given array and create the 2D array of size give. i.e 3x3
print(x)

In [ ]:
arr = np.random.choice(5, 3, replace=False)
arr

In [ ]:
# Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.
# The probability for the value to be 3 is set to be 0.1
# The probability for the value to be 5 is set to be 0.3
# The probability for the value to be 7 is set to be 0.6
# The probability for the value to be 9 is set to be 0

from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.1, 0.1, 0.7], size=(10)) # p = probability of occurance.
print(x)

In [ ]:
# Create 2D array using choice with probability!!!
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

### Shuffle

In [ ]:
# Shuffle means changing arrangement of elements in-place. i.e. in the array itself.
import numpy as np
from numpy import random

arr = [1, 5, 3, 4, 2, 8, 9, 7, 10, 6]
random.shuffle(arr) 
print(arr)

In [ ]:
# The permutation() method returns a re-arranged array (and leaves the original array un-changed).
from numpy import random
import numpy as np

arr = [4, 10, 6, 1, 9, 8, 2, 3, 5, 7]
rand = random.permutation(arr)
rand

In [ ]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr)) 

# The permutation() method returns a re-arranged array (and leaves the original array un-changed).

# Seaborn (Matplotlib)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot([0, 1, 2, 9, 4, 5], hist=False)

plt.show()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot([1, 20, 35, 40, 25, 100], hist=False)

plt.show()

In [ ]:
from numpy import random

x = random.normal(size=(2, 3))

print(x)

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.normal(size=(10, 20)), hist=False)

plt.show()

In [ ]:
from numpy import random

sns.distplot(random.binomial(n=10, p=0.5, size=10), hist=False)

print(x)

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.binomial(n=10, p=0.5, size=1000), hist=True, kde=False)

plt.show()

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.normal(loc=50, scale=5, size=1000), hist=False, label='normal')
sns.distplot(random.binomial(n=100, p=0.5, size=1000), hist=False, label='binomial')

plt.show()

In [ ]:
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.poisson(lam=2, size=1000), kde=False)

plt.show()

# Universal Functions [ufuncs]

In [ ]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

In [ ]:
# 413 Lin number: 6
import numpy as np
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]

z = np.add(x, y) # Add list and put it in z
z

In [ ]:
## Create your own ufunc.
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

In [ ]:
import numpy as np
print(type(np.add))

In [ ]:
import numpy as np

def square(num):
    x = lambda num: num**2
    return(x(num))
    # or directly return this: return(num**2)

mySquare = np.frompyfunc(square, 1, 1)
print('My Square ufunc(10) : ', mySquare(10))
print('My Square ufunc(5) : ', mySquare(5))
print('My Square ufunc(8) : ', mySquare(8))
print('My Square ufunc(150) : ', mySquare(150))
print(mySquare)

In [ ]:
import numpy as np

print(type(np.concatenate))

In [ ]:
import numpy as np

print(type(np.blahblah))

In [433]:
import numpy as np

if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


### Simple Arithmatic Operations

In [434]:
import numpy as np

arr1 = np.array([1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
arr2 = np.array([3, 9, 15, 24, 33, 39, 45, 54, 60, 65, 72])

newAdd = np.add(arr1, arr2)
newAdd

array([  4,  14,  25,  39,  53,  64,  75,  89, 100, 110, 122])

In [435]:
import numpy as np

arr1 = np.array([1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
arr2 = np.array([3, 9, 15, 24, 33, 39, 45, 54, 60, 65, 72])

newAdd = np.subtract(arr2, arr1)
newAdd

array([ 2,  4,  5,  9, 13, 14, 15, 19, 20, 20, 22])

In [436]:
import numpy as np

arr1 = np.array([1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
arr2 = np.array([3, 9, 15, 24, 33, 39, 45, 54, 60, 65, 72])

newAdd = np.multiply(arr2, arr1)
newAdd

array([   3,   45,  150,  360,  660,  975, 1350, 1890, 2400, 2925, 3600])

In [440]:
import numpy as np

arr1 = np.array([1, 5, 10, 15, 20])
arr2 = np.array([3, 9, 15, 24, 33])

newAdd = np.divide(arr2, arr1)
newAdd

array([3.  , 1.8 , 1.5 , 1.6 , 1.65])

In [442]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([1,2,3,4,5,6])

newarr = np.power(arr1, arr2)

print(newarr)

[    1     4    27   256  3125 46656]


In [443]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.mod(arr1, arr2)
print(newarr)

[ 1  6  3  0  0 27]


In [444]:
newarr = np.remainder(arr1, arr2)
print(newarr)

[ 1  6  3  0  0 27]


In [445]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)


(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32))


In [447]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])
print(arr.shape)
newarr = np.absolute(arr)

print(newarr)

(6,)
[1 2 1 2 3 4]


In [452]:
arr = np.array([1,2,3,4,5,6,7,8])
print(np.cumsum(arr))
np.cumsum(arr)


[ 1  3  6 10 15 21 28 36]


array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)